services:
  - type: web
    name: cliniflow2026-web
    runtime: node
    plan: starter
    branch: main
    buildCommand: npm install && npx prisma generate && npm run build
    startCommand: npx prisma db push && npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: cliniflow2026-db
          property: connectionString
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: FOLLOW_UP_CRON_SECRET
        sync: false
databases:
  - name: cliniflow2026-db
    plan: free
