services:
  - type: web
    name: cliniflow2026-web
    runtime: node
    plan: starter
    branch: main
    buildCommand: npm ci && npx prisma generate && DATABASE_URL=$DATABASE_URL npx prisma db push && DATABASE_URL=$DATABASE_URL npx prisma db seed && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: DATABASE_URL_DIRECT
        sync: false
      - key: NEXTAUTH_URL
        sync: false
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: FOLLOW_UP_CRON_SECRET
        sync: false
databases:
  - name: cliniflow2026-db
    plan: free
